const cutScene = [
  {
    content: [
      '-Ring...ring...ring!!!-',
      '*Bẹp!!!*',
      '"Cái báo thức đáng ghét, sáng nào cũng đập mà nó vẫn chạy tốt nhỉ?"',
      '"Bây giờ là 7h15 sáng, ...hừm, đành dậy vậy!"',
      '*Bước tới nhà vệ sinh*',
      '"Mình lười đánh răng quá, dù gì thì ăn sáng xong mùi hôi miệng nó cũng sẽ bị lấn át bởi đồ ăn mà."',
    ],
    idQuestion: 0,
  },
  {
    content: [
      '-Xoạt...xoạt...xoạt!-',
      '"Mình ghét điều này!"',
      '*Đánh răng xong thì tôi xuống bếp để ăn sáng*',
      '"Mẹ ơi, tô bún này của con phải ko?"',
      '"[<i>Mẹ</i>] Con ăn tô có cục giò và 2 lát thịt ấy!"',
      '"Dạ!"',
      '*Ăn xong thì tôi lên con xe máy chị để lại để tới trường*',
      '*Vừa đi vào lớp, thì tôi va phải My đang hớt hải chạy ra*',
      '"[<i>My(Crush của tôi)</i>] Ái! Hôm nay ông lên lớp trễ thế, lát nữa có thuyết trình đấy!"',
      '"Thuyết trình??? thuyết trình cái gì"',
      '*Tôi hoảng hốt vcl ra, theo trí nhớ của tôi thì tuần này làm quái gì thuyết trình*',
      '"[<i>My</i>] Mà ông tới cũng đúng lúc lắm, đi in báo cáo thuyết trình với tui, tui để quên ví ngoài xe rồi."',
    ],
    idQuestion: 1,
  },
  {
    content: [
      '*Đi xuống bếp để ăn sáng*',
      '"Mẹ ơi, tô bún này của con phải ko?"',
      '"[<i>Mẹ</i>] Con ăn tô có cục giò và 2 lát thịt ấy!"',
      '"Dạ!"',
      '*Hít mũi*',
      '"Có mùi gì đó hơi kì nhỉ?"',
      '*Ăn xong thì tôi lên con xe máy chị để lại để tới trường.*',
      '*Vừa đi vào lớp, thì tôi va phải My đang hớt hải chạy ra.*',
      '"[<i>My(Crush của tôi)</i>] Ái! Hôm nay ông lên lớp trễ thế, lát nữa có thuyết trình đấy!"',
      '"Thuyết trình??? thuyết trình cái gì"',
      '*Tôi hoảng hốt vcl ra, theo trí nhớ của tôi thì tuần này làm quái gì thuyết trình*',
      '*My hơi khịt khịt mũi, lấy tay phẩy phẩy nhẹ trước mũi*',
      '"[<i>My</i>] Thuyết trình môn Quản lý dự án, tối qua thầy báo sáng nay lớp sẽ thuyết trình sớm, ông không lên page lớp à?"',
      '*My hơi nhăn mặt*',
      '"[<i>My</i>] Thôi tôi đi in báo cáo thuyết trình đã"',
    ],
    idQuestion: 2,
  },
  {
    content: [
      '*Tôi chạy theo My để bắt kịp cô ấy*',
      '"My có vẻ hơi lo lắng, nhìn cô ấy có vẻ gấp gáp"',
      '*Tôi cùng My đến tiệm photocopy*',
      '"[<i>My</i>] Sáng nay thuyết trình môn Quản lý dự án, tối qua thầy báo sáng nay lớp sẽ thuyết trình sớm..."',
      '"[<i>My</i>] ... vì chiều nay là thầy phải đi công tác gấp rồi, dự là cuối tháng mới về, ông không lên page lớp à?"',
      '"Tối qua tôi làm bài nên tắt wifi để tập trung, làm xong thì ngủ quên mất, nên chẳng biết gì."',
      '*Tôi và cô ấy đang trò chuyện thì có giọng nói phía bên vang lên*',
      '"[<i>Thằng ất ơ nào đấy</i>] Chào em, lâu rồi mới gặp lại em"',
      '*À, tôi nhận thằng này, nó trên tôi 1 khóa, nhưng tôi không thể nào tôn trọng nổi.*',
      '*Vì sao á? Vì nó dám đùa giỡn với crush của tôi*',
      '"[<i>Vẫn là thằng ất ơ đấy</i>] Hôm nay em có môn nào phải báo cáo hả, cần anh giúp gì không?"',
      '*My bị bất ngờ nên cô ấy delay khoảng chừng là 2s rồi mới trả lời*',
      '"[<i>My</i>] Dạ không cần đâu anh.',
      '"Thằng cờ hó này trong trường nổi tiếng xấu là chuyên tán tỉnh thả thính các em khóa dưới"',
      '"Sau khi hắn đạt được mục đích (tôi cũng chưa rõ mục đích là gì) thì hắn sẽ bỏ rơi họ."',
      '"My (của tôi) cũng bị hắn để ý và tán tỉnh, tôi nghe kể là khi cô ấy bắt đầu có cảm tình với hắn..."',
      '"...thì Linh (1 cô bạn khá xinh khác trong lớp) phát hiện hắn đang cặp với 1 đứa khác ở khóa dưới tôi"',
      '"Ít ra thì cô ấy vẫn chưa bị hắn lừa, nhưng tôi vẫn ghét hắn, vì hắn trùng tên với tôi, làm tôi cũng bị ghét lây"',
      '"Tôi nhận ra cô ấy có vẻ lúng túng và không thích nói chuyện với hắn."',
      '"Tôi nên tìm cách giúp cô ấy"',
    ],
    idQuestion: 3,
  },
  {
    content: [
      '*Tôi lưỡng lự từ chối và bước vào lớp và hỏi mấy thằng bạn để làm rõ tình hình*',
      '"Ê Trường, sáng nay có gì hot hả?"',
      '"[<i>Trường</i>] Đệch, sao giờ nay mi mới mò lên, lát nữa có thuyết trình đó"',
      '"Clgt, môn gì vậy ba???"',
      '"[<i>Trường</i>] Môn quản lý dự án, tối qua mới nhắn tin trên page lớp á..."',
      '"[<i>Trường</i>] ...giờ cả lớp ai cũng lo chuẩn bị kìa, mi lo đọc tài liệu soạn hôm cuối tuần đi, lát lên chém gió"',
    ],
    idQuestion: 4,
  },
  {
    content: [
      '*Tôi định giữ My lại nhưng không kịp*',
      '*Tôi đành chạy theo My để bắt kịp cô ấy*',
      '"My có vẻ hơi lo lắng, nhìn cô ấy có vẻ gấp gáp"',
      '*Tôi cùng My đến tiệm photocopy*',
      '*Tôi và cô ấy đang đứng chờ thì có giọng nói phía bên vang lên*',
      '"[<i>Thằng ất ơ nào đấy</i>] Chào em, lâu rồi mới gặp lại em"',
      '*À, tôi nhận thằng này, nó trên tôi 1 khóa, nhưng tôi không thể nào tôn trọng nổi.*',
      '*Vì sao á? Vì nó dám đùa giỡn với crush của tôi*',
      '"[<i>Vẫn là thằng ất ơ đấy</i>] Hôm nay em có môn nào phải báo cáo hả, cần anh giúp gì không?"',
      '*My bị bất ngờ nên cô ấy delay khoảng chừng là 2s rồi mới trả lời*',
      '"[<i>My</i>] Dạ không cần đâu anh.',
      '"Thằng cờ hó này trong trường nổi tiếng xấu là chuyên tán tỉnh thả thính các em khóa dưới"',
      '"Sau khi hắn đạt được mục đích (tôi cũng chưa rõ mục đích là gì) thì hắn sẽ bỏ rơi họ."',
      '"My (của tôi) cũng bị hắn để ý và tán tỉnh, tôi nghe kể là khi cô ấy bắt đầu có cảm tình với hắn..."',
      '"...thì Linh (1 cô bạn khá xinh khác trong lớp) phát hiện hắn đang cặp với 1 đứa khác ở khóa dưới tôi"',
      '"Ít ra thì cô ấy vẫn chưa bị hắn lừa, nhưng tôi vẫn ghét hắn, vì hắn trùng tên với tôi, làm tôi cũng bị ghét lây"',
      '"Tôi nhận ra cô ấy có vẻ lúng túng và không thích nói chuyện với hắn."',
      '"Tôi nên tìm cách giúp cô ấy"',
    ],
    idQuestion: 5,
  },
  {
    content: [
      '*Tôi lưỡng lự bước vào lớp và hỏi mấy thằng bạn để làm rõ tình hình*',
      '"Ê Trường, sáng nay có gì hot hả?"',
      '"[<i>Trường</i>] Đệch, sao giờ nay mi mới mò lên, lát nữa có thuyết trình đó"',
      '"Clgt, môn gì vậy ba???"',
      '"[<i>Trường</i>] Môn quản lý dự án, tối qua mới nhắn tin trên page lớp á..."',
      '"[<i>Trường</i>] ...giờ cả lớp ai cũng lo chuẩn bị kìa, mi lo đọc tài liệu soạn hôm cuối tuần đi, lát lên chém gió"',
      '"[<i>Trường</i>] Mà ra súc miệng đi ba, sáng nay éo đánh răng à! Hôi vl!"',
      '"Ơ, (tôi nói dối trắng trợn) ta đánh rồi mày, đưa tài liệu đây ta xem phát"',
    ],
    idQuestion: 6,
  },
];
